<?php

/**
 * AI-SEO-Captain-Advanced-Cache
 *
 * WordPress advanced-cache.php drop-in.
 * Intercepts requests before WordPress loads to serve cached pages.
 * Generated by the SEO Captain plugin — do not edit manually.
 *
 * @package AI_SEO_Captain
 */

// Security: must be loaded by WordPress.
if (! defined('ABSPATH')) {
    return;
}

// Only handle GET requests.
if (! isset($_SERVER['REQUEST_METHOD']) || 'GET' !== strtoupper($_SERVER['REQUEST_METHOD'])) {
    return;
}

// Never serve cached pages for admin, login, or cron requests.
$request_uri = isset($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] : '';

$skip_paths = array('/wp-admin', '/wp-login', '/wp-cron', '/xmlrpc', '/wp-json');
foreach ($skip_paths as $path) {
    if (false !== strpos($request_uri, $path)) {
        return;
    }
}

// Never serve cached pages to logged-in users (check cookies).
if (! empty($_COOKIE)) {
    foreach (array_keys($_COOKIE) as $cookie_name) {
        if (0 === strpos($cookie_name, 'wordpress_logged_in_')) {
            return;
        }
    }

    // WooCommerce: cart has items — skip cache.
    if (isset($_COOKIE['woocommerce_items_in_cart']) || isset($_COOKIE['woocommerce_cart_hash'])) {
        return;
    }
}

// Skip POST data present.
if (! empty($_POST)) {
    return;
}

// Build the cache file path.
$cache_uri = strtok($request_uri, '?');
if (empty($cache_uri)) {
    $cache_uri = '/';
}

$cache_hash   = md5($cache_uri);
$cache_prefix = substr($cache_hash, 0, 2);
$cache_dir    = WP_CONTENT_DIR . '/cache/ai-seo-captain/pages/';
$cache_file   = $cache_dir . $cache_prefix . '/' . $cache_hash . '.html';
$meta_file    = $cache_dir . $cache_prefix . '/' . $cache_hash . '.meta';

if (! file_exists($cache_file)) {
    return;
}

// Check TTL from meta file.
if (file_exists($meta_file)) {
    $raw_meta = @file_get_contents($meta_file);
    if (false !== $raw_meta) {
        $meta = @unserialize($raw_meta);
        if (is_array($meta) && isset($meta['created'], $meta['ttl'])) {
            if ((time() - (int) $meta['created']) > (int) $meta['ttl']) {
                // Expired — let WordPress handle the request normally.
                @unlink($cache_file);
                @unlink($meta_file);
                return;
            }
        }
    }
}

// Serve the cached page.
header('Content-Type: text/html; charset=UTF-8');
header('X-Cache: HIT');
header('X-Cache-Engine: AI-SEO-Captain');
header('Cache-Control: public, max-age=86400');

$html = @file_get_contents($cache_file);

if (false === $html) {
    return;
}

// GZIP compression if accepted.
if (isset($_SERVER['HTTP_ACCEPT_ENCODING']) && false !== strpos($_SERVER['HTTP_ACCEPT_ENCODING'], 'gzip') && function_exists('gzencode')) {
    header('Content-Encoding: gzip');
    header('Vary: Accept-Encoding');
    echo gzencode($html, 6);
} else {
    echo $html;
}

exit;
