<?php

namespace AI_SEO_Captain\Cache;

/**
 * File-based WordPress object cache with drop-in management.
 */
class Object_Cache
{

    /** @var string */
    private $cache_dir;

    /** @var int TTL in seconds. */
    private $ttl;

    /** @var string Signature to identify our drop-in. */
    private const SIGNATURE = 'AI-SEO-Captain-Object-Cache';

    public function __construct(array $options = array())
    {
        $this->cache_dir = WP_CONTENT_DIR . '/cache/ai-seo-captain/objects/';
        $this->ttl       = isset($options['cache_page_ttl']) ? (int) $options['cache_page_ttl'] : 86400;
    }

    /**
     * Generate the object-cache.php drop-in content.
     */
    public function generate_dropin(): string
    {
        $cache_dir = addslashes($this->cache_dir);

        return <<<'PHP'
<?php
/**
 * AI-SEO-Captain-Object-Cache
 *
 * File-based WordPress object cache drop-in.
 * Generated by the SEO Captain plugin — do not edit manually.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * @global WP_Object_Cache $wp_object_cache
 */
function wp_cache_init() {
    $GLOBALS['wp_object_cache'] = new WP_Object_Cache();
}

function wp_cache_get( $key, $group = 'default', $force = false, &$found = null ) {
    return $GLOBALS['wp_object_cache']->get( $key, $group, $force, $found );
}

function wp_cache_set( $key, $data, $group = 'default', $expire = 0 ) {
    return $GLOBALS['wp_object_cache']->set( $key, $data, $group, $expire );
}

function wp_cache_add( $key, $data, $group = 'default', $expire = 0 ) {
    return $GLOBALS['wp_object_cache']->add( $key, $data, $group, $expire );
}

function wp_cache_replace( $key, $data, $group = 'default', $expire = 0 ) {
    return $GLOBALS['wp_object_cache']->replace( $key, $data, $group, $expire );
}

function wp_cache_delete( $key, $group = 'default' ) {
    return $GLOBALS['wp_object_cache']->delete( $key, $group );
}

function wp_cache_flush() {
    return $GLOBALS['wp_object_cache']->flush();
}

function wp_cache_add_global_groups( $groups ) {
    $GLOBALS['wp_object_cache']->add_global_groups( $groups );
}

function wp_cache_add_non_persistent_groups( $groups ) {
    $GLOBALS['wp_object_cache']->add_non_persistent_groups( $groups );
}

function wp_cache_close() {
    return true;
}

function wp_cache_switch_to_blog( $blog_id ) {
    $GLOBALS['wp_object_cache']->switch_to_blog( $blog_id );
}

class WP_Object_Cache {
    private $cache = array();
    private $cache_dir;
    private $global_groups = array();
    private $non_persistent_groups = array();
    private $blog_prefix = '';
    public $cache_hits = 0;
    public $cache_misses = 0;

    public function __construct() {
        $this->cache_dir = WP_CONTENT_DIR . '/cache/ai-seo-captain/objects/';
        $this->blog_prefix = is_multisite() ? get_current_blog_id() . ':' : '';
    }

    public function get( $key, $group = 'default', $force = false, &$found = null ) {
        $group = $this->sanitize_group( $group );
        $id = $this->build_key( $key, $group );

        if ( ! $force && isset( $this->cache[ $group ][ $key ] ) ) {
            $found = true;
            $this->cache_hits++;
            return $this->cache[ $group ][ $key ];
        }

        if ( in_array( $group, $this->non_persistent_groups, true ) ) {
            $found = false;
            $this->cache_misses++;
            return false;
        }

        $file = $this->get_file_path( $id, $group );

        if ( ! file_exists( $file ) ) {
            $found = false;
            $this->cache_misses++;
            return false;
        }

        $raw = @file_get_contents( $file );
        if ( false === $raw ) {
            $found = false;
            $this->cache_misses++;
            return false;
        }

        $data = @unserialize( $raw );

        if ( false === $data && 'b:0;' !== $raw ) {
            $found = false;
            $this->cache_misses++;
            @unlink( $file );
            return false;
        }

        if ( is_array( $data ) && isset( $data['expires'] ) && $data['expires'] > 0 && time() > $data['expires'] ) {
            $found = false;
            $this->cache_misses++;
            @unlink( $file );
            return false;
        }

        $value = isset( $data['value'] ) ? $data['value'] : false;
        $this->cache[ $group ][ $key ] = $value;
        $found = true;
        $this->cache_hits++;

        return $value;
    }

    public function set( $key, $data, $group = 'default', $expire = 0 ) {
        $group = $this->sanitize_group( $group );
        $this->cache[ $group ][ $key ] = $data;

        if ( in_array( $group, $this->non_persistent_groups, true ) ) {
            return true;
        }

        $id = $this->build_key( $key, $group );
        $file = $this->get_file_path( $id, $group );
        $dir = dirname( $file );

        if ( ! is_dir( $dir ) ) {
            @mkdir( $dir, 0755, true );
        }

        $payload = serialize( array(
            'value'   => $data,
            'expires' => $expire > 0 ? time() + $expire : 0,
        ) );

        return false !== @file_put_contents( $file, $payload, LOCK_EX );
    }

    public function add( $key, $data, $group = 'default', $expire = 0 ) {
        $group = $this->sanitize_group( $group );

        if ( isset( $this->cache[ $group ][ $key ] ) ) {
            return false;
        }

        return $this->set( $key, $data, $group, $expire );
    }

    public function replace( $key, $data, $group = 'default', $expire = 0 ) {
        $group = $this->sanitize_group( $group );

        if ( ! isset( $this->cache[ $group ][ $key ] ) ) {
            $id = $this->build_key( $key, $group );
            $file = $this->get_file_path( $id, $group );
            if ( ! file_exists( $file ) ) {
                return false;
            }
        }

        return $this->set( $key, $data, $group, $expire );
    }

    public function delete( $key, $group = 'default' ) {
        $group = $this->sanitize_group( $group );

        unset( $this->cache[ $group ][ $key ] );

        if ( in_array( $group, $this->non_persistent_groups, true ) ) {
            return true;
        }

        $id = $this->build_key( $key, $group );
        $file = $this->get_file_path( $id, $group );

        if ( file_exists( $file ) ) {
            @unlink( $file );
        }

        return true;
    }

    public function flush() {
        $this->cache = array();
        $this->delete_dir_contents( $this->cache_dir );
        return true;
    }

    public function add_global_groups( $groups ) {
        $groups = (array) $groups;
        $this->global_groups = array_merge( $this->global_groups, $groups );
        $this->global_groups = array_unique( $this->global_groups );
    }

    public function add_non_persistent_groups( $groups ) {
        $groups = (array) $groups;
        $this->non_persistent_groups = array_merge( $this->non_persistent_groups, $groups );
        $this->non_persistent_groups = array_unique( $this->non_persistent_groups );
    }

    public function switch_to_blog( $blog_id ) {
        $this->blog_prefix = is_multisite() ? $blog_id . ':' : '';
    }

    private function sanitize_group( $group ) {
        return empty( $group ) ? 'default' : $group;
    }

    private function build_key( $key, $group ) {
        $prefix = in_array( $group, $this->global_groups, true ) ? '' : $this->blog_prefix;
        return $prefix . $group . ':' . $key;
    }

    private function get_file_path( $id, $group ) {
        $safe_group = preg_replace( '/[^a-zA-Z0-9_-]/', '_', $group );
        return $this->cache_dir . $safe_group . '/' . md5( $id ) . '.php';
    }

    private function delete_dir_contents( $dir ) {
        if ( ! is_dir( $dir ) ) {
            return;
        }

        $items = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator( $dir, \RecursiveDirectoryIterator::SKIP_DOTS ),
            \RecursiveIteratorIterator::CHILD_FIRST
        );

        foreach ( $items as $item ) {
            if ( $item->isDir() ) {
                @rmdir( $item->getPathname() );
            } else {
                @unlink( $item->getPathname() );
            }
        }
    }
}
PHP;
    }

    /**
     * Install the drop-in to wp-content/object-cache.php.
     */
    public function install(): bool
    {
        $dropin_file = WP_CONTENT_DIR . '/object-cache.php';

        // Do not overwrite an existing drop-in from another plugin.
        if (file_exists($dropin_file) && ! $this->is_ours()) {
            return false;
        }

        $content = $this->generate_dropin();

        // Ensure cache directory exists.
        if (! is_dir($this->cache_dir)) {
            wp_mkdir_p($this->cache_dir);
        }

        // Write index.php to prevent directory listing.
        $index_file = $this->cache_dir . 'index.php';
        if (! file_exists($index_file)) {
            // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
            file_put_contents($index_file, '<?php // Silence is golden.');
        }

        // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
        return false !== file_put_contents($dropin_file, $content, LOCK_EX);
    }

    /**
     * Remove the drop-in.
     */
    public function remove(): bool
    {
        $dropin_file = WP_CONTENT_DIR . '/object-cache.php';

        if (! file_exists($dropin_file)) {
            return true;
        }

        if (! $this->is_ours()) {
            return false;
        }

        wp_delete_file($dropin_file);

        return ! file_exists($dropin_file);
    }

    /**
     * Check if our drop-in is active (vs another plugin's).
     */
    public function is_ours(): bool
    {
        $dropin_file = WP_CONTENT_DIR . '/object-cache.php';

        if (! file_exists($dropin_file)) {
            return false;
        }

        // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_get_contents
        $content = file_get_contents($dropin_file);

        return false !== $content && false !== strpos($content, self::SIGNATURE);
    }

    /**
     * Flush all object cache files.
     */
    public function flush(): void
    {
        if (! is_dir($this->cache_dir)) {
            return;
        }

        $items = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($this->cache_dir, \RecursiveDirectoryIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::CHILD_FIRST
        );

        foreach ($items as $item) {
            if ($item->isDir()) {
                @rmdir($item->getPathname());
            } else {
                $name = $item->getFilename();
                if ('index.php' !== $name) {
                    wp_delete_file($item->getPathname());
                }
            }
        }
    }

    /**
     * Get stats.
     */
    public function get_stats(): array
    {
        $stats = array(
            'files' => 0,
            'size'  => 0,
        );

        if (! is_dir($this->cache_dir)) {
            return $stats;
        }

        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($this->cache_dir, \RecursiveDirectoryIterator::SKIP_DOTS)
        );

        foreach ($iterator as $file) {
            if ($file->isFile() && 'php' === $file->getExtension() && 'index.php' !== $file->getFilename()) {
                ++$stats['files'];
                $stats['size'] += $file->getSize();
            }
        }

        return $stats;
    }
}
